apiVersion: v1
kind: Service
metadata:
  name: dnslb-tcp
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: "shared-coredns-ip"
spec:
  loadBalancerIP: 172.17.255.50
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  ports:
    - name: tcpport
      protocol: TCP
      port: 53
      targetPort: 53
    - name: metrics
      protocol: TCP
      port: 9153
