apiVersion: v1
kind: Service
metadata:
  name: dnslb-udp
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: "shared-coredns-ip"
spec:
  loadBalancerIP: 172.17.255.50
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  ports:
    - name: udpport
      protocol: UDP
      port: 53
      targetPort: 53