apiVersion: v1
kind: Service
metadata:
  name: dnslb
  namespace: kube-system
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  ports:
    - name: tcpport
      protocol: TCP
      port: 53
      targetPort: 53
    - name: metrics
      protocol: TCP
      port: 9153
      targetPort: 9153
    - name: udpport
      protocol: UDP
      port: 53
      targetPort: 53