
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-status
  labels:
    app: nginx-status
spec:
  type: ClusterIP
  selector:
    app: nginx-status
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: metrics
    port: 9113
    targetPort: 9113
