apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-status
spec:
  selector:
    matchLabels:
      app: nginx-status
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-status
    spec:
      containers:
        - name: nginx
          image: yunusovtr/nginx-status
          ports:
            - containerPort: 80
        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter:0.11
          args:
            - -nginx.scrape-uri=http://localhost/basic_status
          ports:
            - containerPort: 9113
