---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: svcmonitor
  namespace: default
  labels:
    release: prom
spec:
  endpoints:
    - path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: nginx-status
