apiVersion: v1
kind: Pod
metadata:
  name: mc
  labels:
    app: mc
spec:
  containers:
    - name: mc
      image: minio/mc
      command: ['sleep', 'infinity']
      volumeMounts:
        - name: config
          mountPath: /root/.mc
  initContainers:
    - name: init-mc
      image: minio/mc
      env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: accessKey
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: secretKey
      command: ['mc', 'alias', 'set', 'minio', 'http://minio:9000', '$(MINIO_ACCESS_KEY)', '$(MINIO_SECRET_KEY)']
      volumeMounts:
        - name: config
          mountPath: /root/.mc
  volumes:
    - name: config
      emptyDir: {}
